weblate_web/urls.py
# -*- coding: utf-8 -*-
#
# Copyright © 2012 - 2019 Michal Čihař <michal@cihar.com>
#
# This file is part of Weblate <https://weblate.org/>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView, RedirectView
from django.conf import settings
from django.contrib.sitemaps import Sitemap
import django.contrib.sitemaps.views
import django.views.static

from simple_sso.sso_client.client import Client

from weblate_web.views import (
    PaymentView, CustomerView, CompleteView, fetch_vat,
    DonateView, DonateRewardView, process_donation,
    EditLinkView, download_invoice, disable_repeat,
)


class PagesSitemap(Sitemap):
    '''
    Sitemap of static pages for one language.
    '''
    def __init__(self, language):
        super().__init__()
        self.language = language

    def items(self):
        return (
            ('/', 1.0, 'weekly'),
            ('/features/', 0.9, 'weekly'),
            ('/tour/', 0.9, 'monthly'),
            ('/download/', 0.5, 'daily'),
            ('/try/', 0.5, 'weekly'),
            ('/hosting/', 0.8, 'monthly'),
            ('/contribute/', 0.7, 'monthly'),
            ('/donate/', 0.7, 'weekly'),
            ('/support/', 0.7, 'monthly'),
            ('/thanks/', 0.2, 'monthly'),
            ('/terms/', 0.2, 'monthly'),
        )

    def location(self, obj):
        return '/{0}{1}'.format(self.language, obj[0])

    def priority(self, obj):
        if self.language == 'en':
            return obj[1]
        return obj[1] * 3 / 4

    def changefreq(self, obj):
        # pylint: disable=R0201
        return obj[2]


# create each section in all languages
SITEMAPS = {
    lang[0]: PagesSitemap(lang[0])
    for lang in settings.LANGUAGES
}
UUID = r'(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})'


SSO_CLIENT = Client(
    settings.SSO_SERVER, settings.SSO_PUBLIC_KEY, settings.SSO_PRIVATE_KEY
)


urlpatterns = i18n_patterns(
    url(
        r'^$',
        TemplateView.as_view(template_name="index.html"),
        name='home'
    ),
    url(
        r'^features/$',
        TemplateView.as_view(template_name="features.html"),
        name='features'
    ),
    url(
        r'^tour/$',
        TemplateView.as_view(template_name="tour.html"),
        name='tour'
    ),
    url(
        r'^download/$',
        TemplateView.as_view(template_name="download.html"),
        name='download'
    ),
    url(
        r'^try/$',
        TemplateView.as_view(template_name="try.html"),
        name='try'
    ),
    url(
        r'^hosting/$',
        TemplateView.as_view(template_name="hosting.html"),
        name='hosting'
    ),
    url(
        r'^hosting/free/$',
        TemplateView.as_view(template_name="hosting-free.html"),
        name='hosting-free'
    ),
    url(
        r'^hosting/ordered/$',
        TemplateView.as_view(template_name="hosting-ordered.html"),
        name='hosting-ordered'
    ),
    url(
        r'^contribute/$',
        TemplateView.as_view(template_name="contribute.html"),
        name='contribute'
    ),
    url(
        r'^donate/$',
        TemplateView.as_view(template_name="donate.html"),
        name='donate'
    ),
    url(
        r'^donate/process/$',
        process_donation,
        name='donate-process'
    ),
    url(
        r'^donate/new/$',
        DonateView.as_view(),
        name='donate-new'
    ),
    url(
        r'^donate/new/' + UUID + '/$',
        DonateRewardView.as_view(),
        name='donate-reward'
    ),
    url(
        r'^donate/edit/(?P<pk>[0-9]+)/$',
        EditLinkView.as_view(),
        name='donate-edit'
    ),
    url(
        r'^donate/invoice/' + UUID + '/$',
        download_invoice,
        name='donate-invoice'
    ),
    url(
        r'^donate/disable/(?P<pk>[0-9]+)/$',
        disable_repeat,
        name='donate-disable'
    ),
    url(
        r'^support/$',
        TemplateView.as_view(template_name="support.html"),
        name='support'
    ),
    url(
        r'^thanks/$',
        TemplateView.as_view(template_name="thanks.html"),
        name='thanks'
    ),
    url(
        r'^terms/$',
        TemplateView.as_view(template_name="terms.html"),
        name='terms'
    ),
    url(
        r'^payment/' + UUID + '/$',
        PaymentView.as_view(),
        name='payment'
    ),
    url(
        r'^payment/' + UUID + '/edit/$',
        CustomerView.as_view(),
        name='payment-customer'
    ),
    url(
        r'^payment/' + UUID + '/complete/$',
        CompleteView.as_view(),
        name='payment-complete'
    ),

    # Compatibility with disabled languages
    url(
        r'^[a-z][a-z]/$',
        RedirectView.as_view(url='/', permanent=False)
    ),
    url(
        r'^[a-z][a-z]_[A-Z][A-Z]/$',
        RedirectView.as_view(url='/', permanent=False)
    ),
    # Broken links
    url(
        r'^https?:/.*$',
        RedirectView.as_view(url='/', permanent=True)
    ),
    url(
        r'^index\.html$',
        RedirectView.as_view(url='/', permanent=True)
    ),
    url(
        r'^index\.([a-z][a-z])\.html$',
        RedirectView.as_view(url='/', permanent=True)
    ),
    url(
        r'^[a-z][a-z]/index\.html$',
        RedirectView.as_view(url='/', permanent=True)
    ),
    url(
        r'^[a-z][a-z]_[A-Z][A-Z]/index\.html$',
        RedirectView.as_view(url='/', permanent=True)
    ),
) + [
    url(
        r'^sitemap\.xml$',
        django.contrib.sitemaps.views.sitemap,
        {'sitemaps': SITEMAPS}
    ),
    url(
        r'^js/vat/$',
        fetch_vat
    ),
    url(r'^sso-login/', include(SSO_CLIENT.get_urls())),
    url(r'^logout/$', LogoutView.as_view(next_page='/'), name='logout'),
    # Admin
    url(r'^admin/', admin.site.urls),

    # Media files on devel server
    url(
        r'^media/(?P<path>.*)$',
        django.views.static.serve,
        {'document_root': settings.MEDIA_ROOT}
    ),
]

weblate_web/models.py
# -*- coding: utf-8 -*-
#
# Copyright © 2012 - 2019 Michal Čihař <michal@cihar.com>
#
# This file is part of Weblate <https://weblate.org/>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

import uuid

from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone
from django.utils.functional import cached_property
from django.utils.translation import ugettext_lazy, ugettext

from wlhosted.payments.models import (
    Payment, RECURRENCE_CHOICES, get_period_delta,
)

PAYMENTS_ORIGIN = 'https://weblate.org/donate/process/'


class Reward(models.Model):
    uuid = models.UUIDField(
        primary_key=True, default=uuid.uuid4, editable=False
    )
    recurring = models.CharField(
        choices=RECURRENCE_CHOICES,
        default='',
        blank=True,
        max_length=10,
    )
    amount = models.PositiveIntegerField()
    has_link = models.BooleanField(blank=True)
    thanks_link = models.BooleanField(blank=True, db_index=True)
    third_party = models.BooleanField(blank=True)
    active = models.BooleanField(blank=True)
    name = models.CharField(max_length=200)

    class Meta:
        index_together = [
            ('active', 'third_party'),
        ]

    def get_absolute_url(self):
        return reverse('donate-reward', kwargs={'pk': self.pk})

    def get_display_name(self):
        return ugettext(self.name)

    def __str__(self):
        return self.name


class Donation(models.Model):
    user = models.ForeignKey(User, on_delete=models.deletion.CASCADE)
    payment = models.UUIDField()
    reward = models.ForeignKey(
        Reward, on_delete=models.deletion.CASCADE, null=True, blank=True
    )
    link_text = models.CharField(
        verbose_name=ugettext_lazy('Link text'),
        max_length=200, blank=True
    )
    link_url = models.URLField(
        verbose_name=ugettext_lazy('Link URL'),
        blank=True
    )
    created = models.DateTimeField(auto_now_add=True)
    expires = models.DateTimeField()
    active = models.BooleanField(blank=True, db_index=True)

    @cached_property
    def payment_obj(self):
        return Payment.objects.get(pk=self.payment)

    def list_payments(self):
        initial = Payment.objects.filter(pk=self.payment)
        return initial | initial[0].payment_set.all()

    def get_absolute_url(self):
        return reverse('donate-edit', kwargs={'pk': self.pk})

    def get_amount(self):
        return self.payment_obj.amount


def process_payment(payment):
    if payment.state != Payment.ACCEPTED:
        raise ValueError('Can not process not accepted payment')
    if payment.repeat:
        # Update existing
        donation = Donation.objects.get(payment=payment.repeat.pk)
        donation.expires += get_period_delta(payment.repeat.recurring)
        donation.save()
    else:
        user = User.objects.get(pk=payment.customer.user_id)
        reward = None
        if 'reward' in payment.extra:
            reward = Reward.objects.get(pk=payment.extra['reward'])
        # Calculate expiry
        expires = timezone.now()
        if reward:
            expires += get_period_delta(reward.recurring)
        elif payment.recurring:
            expires += get_period_delta(payment.recurring)
        # Create new
        donation = Donation.objects.create(
            user=user,
            payment=payment.pk,
            reward=reward,
            expires=expires,
            active=True,
        )
    # Flag payment as processed
    payment.state = Payment.PROCESSED
    payment.save()
    return donation

weblate_web/forms.py
# -*- coding: utf-8 -*-
#
# Copyright © 2012 - 2019 Michal Čihař <michal@cihar.com>
#
# This file is part of Weblate <https://weblate.org/>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

from __future__ import unicode_literals

from django import forms
from django.utils.translation import ugettext_lazy as _

from wlhosted.payments.backends import list_backends
from wlhosted.payments.models import RECURRENCE_CHOICES

from weblate_web.models import Donation


class MethodForm(forms.Form):
    method = forms.ChoiceField(
        choices=[],
        required=True,
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['method'].choices = [
            (backend.name, backend.verbose) for backend in list_backends()
        ]


class DonateForm(forms.Form):
    recurring = forms.ChoiceField(
        label=_('Donation recurrence'),
        choices=RECURRENCE_CHOICES,
        initial='m',
        widget=forms.RadioSelect,
    )
    amount = forms.IntegerField(
        label=_('Amount in EUR'),
        min_value=2,
        initial=10,
    )


class EditLinkForm(forms.ModelForm):
    class Meta:
        model = Donation
        fields = ('link_text', 'link_url')

weblate_web/templates/donate/edit.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block title %}{% trans "Donate to Weblate" %}{% endblock %}
{% block header %}{% trans "Donate to Weblate" %}{% endblock %}
{% block description %}
{% block headline %}{% trans "Weblate is provided free of charge, and welcomes donations." %}{% endblock %}
{% endblock %}
{% block content %}

<div class="alert alert-info" role="alert">
  {% trans "Please select choose wanted reward or enter custom donation amount." %}
</div>

<form method="post">
  <div class="card-deck mb-3">
{% csrf_token %}
<div class="card mb-4 shadow-sm">
  <h5 class="card-header">
    {% trans "Edit your reward link" %}
  </h5>
  <div class="card-body">
    {{ form|crispy }}
  </div>
  <div class="card-footer">
    <input type="submit" value="{% trans "Save" %}" class="btn btn-success">
  </div>
</div>
  </div>
</form>

{% endblock %}

weblate_web/templates/donate/form.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block title %}{% trans "Donate to Weblate" %}{% endblock %}
{% block header %}{% trans "Donate to Weblate" %}{% endblock %}
{% block description %}
{% block headline %}{% trans "Weblate is provided free of charge, and welcomes donations." %}{% endblock %}
{% endblock %}
{% block content %}

{% if show_form %}
<div class="alert alert-info" role="alert">
  {% trans "Please choose wanted reward or enter custom donation amount." %}
</div>
{% endif %}

  <div class="card-deck mb-3 text-center">
{% for reward in rewards %}
        <div class="card mb-4 shadow-sm">
          <h5 class="card-header">
            {{ reward.get_display_name }}
          </h5>
          <div class="card-body">
            <table>
            <tr><th>{% trans "Donation recurrence" %}</th><td>{{ reward.get_recurring_display }}</td></tr>
            <tr><th>{% trans "Amount in EUR" %}</th><td>{{ reward.amount }} EUR</td></tr>
            </table>
          </div>
          <div class="card-footer">
            <form method="post">
            {% csrf_token %}
            <input type="hidden" name="reward" value="{{ reward.pk }}">
            <input type="submit" class="btn btn-info btn-block" value="{% trans "Select" %}">
            </form>
          </div>
        </div>
{% endfor %}
  </div>

<div class="alert alert-info" role="alert">
  {% trans "We might refuse to place your link, especially if the site contains adult or illegal content. Please consult us in advance if unsure." %}
</div>

{% if show_form %}
<form method="post">
  <div class="card-deck mb-3">
{% csrf_token %}
<div class="card mb-4 shadow-sm">
  <h5 class="card-header">
    {% trans "Choose your own donation amount" %}
  </h5>
  <div class="card-body">
    {{ form|crispy }}
  </div>
  <div class="card-footer">
    <input type="submit" value="{% trans "Continue" %}" class="btn btn-success">
  </div>
</div>
  </div>
</form>
{% endif %}

{% endblock %}

weblate_web/templates/donate/rewards.html
{% load i18n %}
{% trans "Link placement on the weblate.org thanks page" %}
{% trans "Link placement in the list of supporters" %}
{% trans "Name placement in the list of supporters" %}