weblate_web/urls.py
# -*- coding: utf-8 -*-
#
# Copyright © 2012 - 2019 Michal Čihař <michal@cihar.com>
#
# This file is part of Weblate <https://weblate.org/>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView, RedirectView
from django.conf import settings
from django.contrib.sitemaps import Sitemap
import django.contrib.sitemaps.views
import django.views.static

from simple_sso.sso_client.client import Client

from weblate_web.views import (
    PaymentView, CustomerView, CompleteView, fetch_vat,
    DonateView, DonateRewardView, process_donation,
    EditLinkView, download_invoice, disable_repeat,
)


class PagesSitemap(Sitemap):
    '''
    Sitemap of static pages for one language.
    '''
    def __init__(self, language):
        super().__init__()
        self.language = language

    def items(self):
        return (
            ('/', 1.0, 'weekly'),
            ('/features/', 0.9, 'weekly'),
            ('/tour/', 0.9, 'monthly'),
            ('/download/', 0.5, 'daily'),
            ('/try/', 0.5, 'weekly'),
            ('/hosting/', 0.8, 'monthly'),
            ('/contribute/', 0.7, 'monthly'),
            ('/donate/', 0.7, 'weekly'),
            ('/support/', 0.7, 'monthly'),
            ('/thanks/', 0.2, 'monthly'),
            ('/terms/', 0.2, 'monthly'),
        )

    def location(self, obj):
        return '/{0}{1}'.format(self.language, obj[0])

    def priority(self, obj):
        if self.language == 'en':
            return obj[1]
        return obj[1] * 3 / 4

    def changefreq(self, obj):
        # pylint: disable=R0201
        return obj[2]


# create each section in all languages
SITEMAPS = {
    lang[0]: PagesSitemap(lang[0])
    for lang in settings.LANGUAGES
}
UUID = r'(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})'


SSO_CLIENT = Client(
    settings.SSO_SERVER, settings.SSO_PUBLIC_KEY, settings.SSO_PRIVATE_KEY
)


urlpatterns = i18n_patterns(
    url(
        r'^$',
        TemplateView.as_view(template_name="index.html"),
        name='home'
    ),
    url(
        r'^features/$',
        TemplateView.as_view(template_name="features.html"),
        name='features'
    ),
    url(
        r'^tour/$',
        TemplateView.as_view(template_name="tour.html"),
        name='tour'
    ),
    url(
        r'^download/$',
        TemplateView.as_view(template_name="download.html"),
        name='download'
    ),
    url(
        r'^try/$',
        TemplateView.as_view(template_name="try.html"),
        name='try'
    ),
    url(
        r'^hosting/$',
        TemplateView.as_view(template_name="hosting.html"),
        name='hosting'
    ),
    url(
        r'^hosting/free/$',
        TemplateView.as_view(template_name="hosting-free.html"),
        name='hosting-free'
    ),
    url(
        r'^hosting/ordered/$',
        TemplateView.as_view(template_name="hosting-ordered.html"),
        name='hosting-ordered'
    ),
    url(
        r'^contribute/$',
        TemplateView.as_view(template_name="contribute.html"),
        name='contribute'
    ),
    url(
        r'^donate/$',
        TemplateView.as_view(template_name="donate.html"),
        name='donate'
    ),
    url(
        r'^donate/process/$',
        process_donation,
        name='donate-process'
    ),
    url(
        r'^donate/new/$',
        DonateView.as_view(),
        name='donate-new'
    ),
    url(
        r'^donate/new/' + UUID + '/$',
        DonateRewardView.as_view(),
        name='donate-reward'
    ),
    url(
        r'^donate/edit/(?P<pk>[0-9]+)/$',
        EditLinkView.as_view(),
        name='donate-edit'
    ),
    url(
        r'^donate/invoice/' + UUID + '/$',
        download_invoice,
        name='donate-invoice'
    ),
    url(
        r'^donate/disable/(?P<pk>[0-9]+)/$',
        disable_repeat,
        name='donate-disable'
    ),
    url(
        r'^support/$',
        TemplateView.as_view(template_name="support.html"),
        name='support'
    ),
    url(
        r'^thanks/$',
        TemplateView.as_view(template_name="thanks.html"),
        name='thanks'
    ),
    url(
        r'^terms/$',
        TemplateView.as_view(template_name="terms.html"),
        name='terms'
    ),
    url(
        r'^payment/' + UUID + '/$',
        PaymentView.as_view(),
        name='payment'
    ),
    url(
        r'^payment/' + UUID + '/edit/$',
        CustomerView.as_view(),
        name='payment-customer'
    ),
    url(
        r'^payment/' + UUID + '/complete/$',
        CompleteView.as_view(),
        name='payment-complete'
    ),

    # Compatibility with disabled languages
    url(
        r'^[a-z][a-z]/$',
        RedirectView.as_view(url='/', permanent=False)
    ),
    url(
        r'^[a-z][a-z]_[A-Z][A-Z]/$',
        RedirectView.as_view(url='/', permanent=False)
    ),
    # Broken links
    url(
        r'^https?:/.*$',
        RedirectView.as_view(url='/', permanent=True)
    ),
    url(
        r'^index\.html$',
        RedirectView.as_view(url='/', permanent=True)
    ),
    url(
        r'^index\.([a-z][a-z])\.html$',
        RedirectView.as_view(url='/', permanent=True)
    ),
    url(
        r'^[a-z][a-z]/index\.html$',
        RedirectView.as_view(url='/', permanent=True)
    ),
    url(
        r'^[a-z][a-z]_[A-Z][A-Z]/index\.html$',
        RedirectView.as_view(url='/', permanent=True)
    ),
) + [
    url(
        r'^sitemap\.xml$',
        django.contrib.sitemaps.views.sitemap,
        {'sitemaps': SITEMAPS}
    ),
    url(
        r'^js/vat/$',
        fetch_vat
    ),
    url(r'^sso-login/', include(SSO_CLIENT.get_urls())),
    url(r'^logout/$', LogoutView.as_view(next_page='/'), name='logout'),
    # Admin
    url(r'^admin/', admin.site.urls),

    # Media files on devel server
    url(
        r'^media/(?P<path>.*)$',
        django.views.static.serve,
        {'document_root': settings.MEDIA_ROOT}
    ),
]

weblate_web/models.py
# -*- coding: utf-8 -*-
#
# Copyright © 2012 - 2019 Michal Čihař <michal@cihar.com>
#
# This file is part of Weblate <https://weblate.org/>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

import uuid

from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone
from django.utils.functional import cached_property
from django.utils.translation import ugettext_lazy, ugettext

from wlhosted.payments.models import (
    Payment, RECURRENCE_CHOICES, get_period_delta,
)

PAYMENTS_ORIGIN = 'https://weblate.org/donate/process/'


class Reward(models.Model):
    uuid = models.UUIDField(
        primary_key=True, default=uuid.uuid4, editable=False
    )
    recurring = models.CharField(
        choices=RECURRENCE_CHOICES,
        default='',
        blank=True,
        max_length=10,
    )
    amount = models.PositiveIntegerField()
    has_link = models.BooleanField(blank=True)
    thanks_link = models.BooleanField(blank=True, db_index=True)
    third_party = models.BooleanField(blank=True)
    active = models.BooleanField(blank=True)
    name = models.CharField(max_length=200)

    class Meta:
        index_together = [
            ('active', 'third_party'),
        ]

    def get_absolute_url(self):
        return reverse('donate-reward', kwargs={'pk': self.pk})

    def get_display_name(self):
        return ugettext(self.name)

    def __str__(self):
        return self.name


class Donation(models.Model):
    user = models.ForeignKey(User, on_delete=models.deletion.CASCADE)
    payment = models.UUIDField()
    reward = models.ForeignKey(
        Reward, on_delete=models.deletion.CASCADE, null=True, blank=True
    )
    link_text = models.CharField(
        verbose_name=ugettext_lazy('Link text'),
        max_length=200, blank=True
    )
    link_url = models.URLField(
        verbose_name=ugettext_lazy('Link URL'),
        blank=True
    )
    created = models.DateTimeField(auto_now_add=True)
    expires = models.DateTimeField()
    active = models.BooleanField(blank=True, db_index=True)

    @cached_property
    def payment_obj(self):
        return Payment.objects.get(pk=self.payment)

    def list_payments(self):
        initial = Payment.objects.filter(pk=self.payment)
        return initial | initial[0].payment_set.all()

    def get_absolute_url(self):
        return reverse('donate-edit', kwargs={'pk': self.pk})

    def get_amount(self):
        return self.payment_obj.amount


def process_payment(payment):
    if payment.state != Payment.ACCEPTED:
        raise ValueError('Can not process not accepted payment')
    if payment.repeat:
        # Update existing
        donation = Donation.objects.get(payment=payment.repeat.pk)
        donation.expires += get_period_delta(payment.repeat.recurring)
        donation.save()
    else:
        user = User.objects.get(pk=payment.customer.user_id)
        reward = None
        if 'reward' in payment.extra:
            reward = Reward.objects.get(pk=payment.extra['reward'])
        # Calculate expiry
        expires = timezone.now()
        if reward:
            expires += get_period_delta(reward.recurring)
        elif payment.recurring:
            expires += get_period_delta(payment.recurring)
        # Create new
        donation = Donation.objects.create(
            user=user,
            payment=payment.pk,
            reward=reward,
            expires=expires,
            active=True,
        )
    # Flag payment as processed
    payment.state = Payment.PROCESSED
    payment.save()
    return donation

weblate_web/forms.py
# -*- coding: utf-8 -*-
#
# Copyright © 2012 - 2019 Michal Čihař <michal@cihar.com>
#
# This file is part of Weblate <https://weblate.org/>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

from __future__ import unicode_literals

from django import forms
from django.utils.translation import ugettext_lazy as _

from wlhosted.payments.backends import list_backends
from wlhosted.payments.models import RECURRENCE_CHOICES

from weblate_web.models import Donation


class MethodForm(forms.Form):
    method = forms.ChoiceField(
        choices=[],
        required=True,
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['method'].choices = [
            (backend.name, backend.verbose) for backend in list_backends()
        ]


class DonateForm(forms.Form):
    recurring = forms.ChoiceField(
        label=_('Donation recurrence'),
        choices=RECURRENCE_CHOICES,
        initial='m',
        widget=forms.RadioSelect,
    )
    amount = forms.IntegerField(
        label=_('Amount in EUR'),
        min_value=2,
        initial=10,
    )


class EditLinkForm(forms.ModelForm):
    class Meta:
        model = Donation
        fields = ('link_text', 'link_url')

weblate_web/templates/base-features.html
{% load i18n %}

<div class="col-lg-4 col-sm-6 feature">
<a class="text-info" href="https://docs.weblate.org/en/latest/faq.html#how-to-create-automatic-worflow">
<div class="fas fa-cogs fa-4x"></div>
<h4>{% trans "Continuous translation" %}</h4>
<p>{% trans "Automated translation process can closely follow development of your project." %}</p>
</a>
</div>

<div class="col-lg-4 col-sm-6 feature">
<a class="text-info" href="https://docs.weblate.org/en/latest/user/checks.html">
<div class="fas fa-search fa-4x"></div>
<h4>{% trans "Quality checks" %}</h4>
<p>{% trans "Customizable quality checks will help you in improving quality of translations." %}</p>
</a>
</div>

<div class="col-lg-4 col-sm-6 feature">
<a class="text-info" href="https://docs.weblate.org/en/latest/faq.html#how-does-weblate-credit-translators">
<div class="fas fa-user fa-4x"></div>
<h4>{% trans "Attribution" %}</h4>
<p>{% trans "All your translators will be properly credited in the version control system." %}</p>
</a>
</div>

<div class="col-lg-4 col-sm-6 feature">
<a class="text-info" href="{% url 'hosting' %}">
<div class="fas fa-server fa-4x"></div>
<h4>{% trans "Hosting plans" %}</h4>
<p>{% trans "Hosting plans to use Weblate as a service starting at 19 EUR." %}</p>
</a>
</div>

<div class="col-lg-4 col-sm-6 feature">
<a class="text-info" href="{% url 'download' %}">
<div class="fas fa-cloud fa-4x"></div>
<h4>{% trans "Ready for cloud" %}</h4>
<p>{% trans "Weblate comes with appliances, which are ready to deploy in your cloud." %}</p>
</a>
</div>

<div class="col-lg-4 col-sm-6 feature">
<a class="text-info" href="https://github.com/WeblateOrg/weblate">
<div class="fab fa-github fa-4x"></div>
<h4>{% trans "Free software" %}</h4>
<p>{% trans "Weblate is free software, you can run your own instance of it." %}</p>
</a>
</div>

weblate_web/templates/donate.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "Donate to Weblate" %}{% endblock %}
{% block header %}{% trans "Donate to Weblate" %}{% endblock %}
{% block description %}
{% block headline %}{% trans "Weblate is provided free of charge, and welcomes donations." %}{% endblock %}
{% endblock %}
{% block extrajumbo %}
<p>

<a class="btn btn-info btn-lg" href="{% url 'hosting' %}" role="button"><i class="fas fa-server"></i> {% trans "Purchase hosting package" %}</a>
<a class="btn btn-info btn-lg" href="{% url 'support' %}"><i class="fas fa-life-ring"></i> {% trans "Get support for Weblate" %}</a>

</p>
{% endblock %}
{% block content %}

{% if not user.is_authenticated %}
<a class="btn btn-info float-right" href="{% url 'simple-sso-login' %}?next={% url 'donate' %}"><i class="fas fa-sign-in-alt"></i> {% trans "Sign in to manage your donations" %}</a>
{% else %}
<a class="btn btn-info float-right" href="{% url 'logout' %}?next={% url 'donate' %}"><i class="fas fa-sign-out-alt"></i> {% trans "Sign out" %}</a>
{% with donations=user.donation_set.all %}
{% if donations %}
<h2>{% trans "Your donations" %}</h2>

<table class="table">
<thead>
<tr>
<th>{% trans "Creation date" %}</th>
<th>{% trans "Reward" %}</th>
<th>{% trans "Expiry date" %}</th>
<th>{% trans "Renewal" %}</th>
<th>{% trans "Payments" %}</th>
</tr>
</thead>
<tbody>
{% for donation in donations %}
<tr>
<td>{{ donation.created }}</td>
<td>
{% if donation.reward %}
{{ donation.reward.get_display_name }}
<a class="btn btn-info btn-sm" href="{% url "donate-edit" pk=donation.pk %}">{% trans "Edit" %}</a>
{% else %}
{% trans "No reward" %}
{% endif %}
</td>
<td>
{{ donation.expires }}
</td>
<td>
{% if not donation.active %}
{% trans "Expired" %}
{% elif donation.payment_obj.recurring %}
<form class="form-inline" method="post" action="{% url "donate-disable" pk=donation.pk %}">
{% csrf_token %}
<input type="submit" class="btn btn-warning btn-sm" value="{% trans "Disable renewal" %}">
</form>
{% else %}
{% trans "Does not renew" %}
{% endif %}
</td>
<td>
<ul class="list-unstyled">
{% for payment in donation.list_payments %}
<li>
{{ payment.amount }} EUR 
{% if payment.state == 5 %} 
{% if payment.invoice_filename_valid %}
(<a href="{% url 'donate-invoice' pk=payment.pk %}">{{ payment.invoice_filename }}</a>)
{% else %}
({{ payment.invoice_filename }})
{% endif %}
{% else %}
{{ payment.get_state_display }}
{% if payment.details.reject_reason %}
({{ payment.details.reject_reason }})
{% endif %}
{% endif %}
</li>
{% endfor %}
</ul>
</td>
</tr>
{% endfor %}
</tbody>
</table>
{% endif %}
{% endwith %}
{% endif %}

<h2>{% trans "Donations" %}</h2>

<p>
{% blocktrans %}Recurring donations allow sustainability of Weblate development and help to fund free hosting for libre software. You don't have to spend big money, every penny counts.{% endblocktrans %}
</p>

    <div class="container">
      <div class="card-deck mb-3 text-center">

        <div class="card mb-4 shadow-sm">
          <div class="card-header">
            <h4 class="my-0 font-weight-normal">{% trans "Recurring donation" %}</h4>
          </div>
          <div class="card-body">
            <p>{% trans "Repeated appreciation of the Weblate project helps in keeping the project sustainable in the long term." %}</p>
            <p>{% trans "Please consider this if you are using Weblate on premise without support contract." %}</p>
          </div>
          <div class="card-footer">
            <a href="{% url "donate-new" %}?recurring=m" class="btn btn-lg btn-block btn-info"><i class="fas fa-donate"></i> {% trans "Donate" %}</a>
          </div>
        </div>

        <div class="card mb-4 shadow-sm">
          <div class="card-header">
            <h4 class="my-0 font-weight-normal">{% trans "One time donation" %}</h4>
          </div>
          <div class="card-body">
            <p>{% trans "One time donations are great for appreciating our work on single issue or support." %}</p>
          </div>
          <div class="card-footer">
            <a href="{% url "donate-new" %}?recurring=" class="btn btn-lg btn-block btn-info"><i class="fas fa-donate"></i> {% trans "Donate" %}</a>
          </div>
        </div>

        <div class="card mb-4 shadow-sm">
          <div class="card-header">
            <h4 class="my-0 font-weight-normal">{% trans "Use our services" %}</h4>
          </div>
          <div class="card-body">
            <p>{% trans "Commercial services like hosting or support for on premise installation help funding Weblate development." %}</p>
          </div>
          <div class="card-footer">
            <a class="btn btn-info btn-lg btn-block" href="{% url 'hosting' %}" role="button"><i class="fas fa-server"></i> {% trans "Purchase hosting package" %}</a>
            <a class="btn btn-info btn-lg btn-block" href="{% url 'support' %}"><i class="fas fa-life-ring"></i> {% trans "Get support for Weblate" %}</a>
          </div>
        </div>

      </div>
    </div>


<h2 id="crypto">{% trans "Cryptocurrencies" %}</h2>

<p>
{% blocktrans with "https://trezor.io?offer_id=12&amp;aff_id=1592" as url %}Thanks to <a href="{{ url }}">Trezor</a>, we will gladly accept donations in several cryptocurrencies. You can use the addresses in table below.{% endblocktrans %}
</p>

<table class="table table-bordered table-striped">
<thead class="thead-dark">
<tr><th>{% trans "Currency" %}</th><th>{% trans "Donation address" %}</th></tr>
</thead>
<tbody>
<tr><td><a href="bitcoin:36pK1Yso2ZYv5xLR36wgUzQ7AHDk7i6hwU">Bitcoin</a></td><td>36pK1Yso2ZYv5xLR36wgUzQ7AHDk7i6hwU</td></tr>
<tr><td><a href="litecoin:MTYACnktCc32n3GRhQDfdDyzqSDnQr2tzy">Litecoin</a></td><td>MTYACnktCc32n3GRhQDfdDyzqSDnQr2tzy</td></tr>
<tr><td><a href="dash:XoXrWTmZf7ar9P9tpXHm2JuvpvAwSbbgNh">DASH</a></td><td>XoXrWTmZf7ar9P9tpXHm2JuvpvAwSbbgNh</td></tr>
<tr><td><a href="zcash:t1PSe8FpKfnRJk6XTHkJKCwx4tseSxHr3Z5">Zcash</a></td><td>t1PSe8FpKfnRJk6XTHkJKCwx4tseSxHr3Z5</td></tr>
<tr><td><a href="ethereum:0xE5cd6Fe38af85f68B377AEBCF97Fea2C9683ee0c">Ethereum</a></td><td>0xE5cd6Fe38af85f68B377AEBCF97Fea2C9683ee0c</td></tr>
<tr><td><a href="monero:89A8YoXSErG6X3aTGf96tfCXTJv2kmUUQJucmS8WWuz8S1ftZGAiBKuW66qbV8KDqBSyK8eQBu76PUBi3QUmhY7VFpQ9gbi">Monero</a></td><td>89A8YoXSErG6X3aTGf96tfCXTJv2kmUUQJucmS8WWuz8S1ftZGAiBKuW66qbV8KDqBSyK8eQBu76PUBi3QUmhY7VFpQ9gbi</td></tr>
</tbody>
</table>

{% endblock %}

weblate_web/templates/download-link.html
{% load i18n %}

<a href="{{ base }}{{ name }}">{{ text }} ({{ size }})</a>
<a href="{{ base }}{{ name }}.asc" title="{% trans "PGP signature" %}"><i class="fas fa-file-signature"></i></a>

weblate_web/templates/download.html
{% extends "base.html" %}
{% load i18n %}
{% load downloads %}
{% block title %}{% trans "Download Weblate" %}{% endblock %}
{% block header %}{% trans "Download Weblate" %}{% endblock %}
{% block description %}
{% block headline %}{% trans "Weblate comes with complete source code." %}{% endblock %}
{% endblock %}

{% block extrajumbo %}
<p>
<a class="btn btn-info btn-lg" href="https://github.com/WeblateOrg/weblate/" role="button"><i class="fab fa-github"></i> {% trans "View sources" %}</a>
<a class="btn btn-info btn-lg" href="{% url 'support' %}"><i class="fas fa-life-ring"></i> {% trans "Get support for Weblate" %}</a>
</p>
{% endblock %}
{% block content %}

<h2>{% trans "Download" %}</h2>

<p>
{% blocktrans %}You can download latest release here:{% endblocktrans %}
</p>

<ul>
{% for download in downloads %}
<li>{% downloadlink download %}</li>
{% endfor %}
</ul>

<h2>{% trans "Weblate command line client" %}</h2>

<p>
{% blocktrans with 'https://pypi.python.org/pypi/wlc' as url %}You can control Weblate remotely using <a href="{{ url }}">wlc</a>, it can be installed by using Python PIP:{% endblocktrans %}
</p>

<pre>
pip3 install wlc
</pre>

<p>{% trans "You can also install using packages for following Linux distributions:" %}</p>

<ul>
<li><a href="https://packages.debian.org/wlc">Debian</a>
</ul>


<h2>{% trans "Cloud or virtualization images" %}</h2>

<p>{% trans "Weblate can be run in any cloud or virtualization environment. Following links will show you information about some of these:" %}</p>

<ul>
<li><a href="https://docs.weblate.org/en/latest/admin/deployments.html#docker">{% trans "Running Weblate in a Docker container" %}</a></li>
<li><a href="https://docs.weblate.org/en/latest/admin/deployments.html#openshift">{% trans "Running Weblate on OpenShift platform" %}</a></li>
<li><a href="https://bitnami.com/stack/weblate">{% trans "BitNami Weblate stack providing native installation for most platforms as well as support for many public cloud providers" %}</a></li>
</ul>

<a href="https://docs.weblate.org/en/latest/admin/deployments.html#docker"><img src="/media/docker.png" /></a>
<a href="https://docs.weblate.org/en/latest/admin/deployments.html#openshift"><img src="/media/openshift.png" /></a>
<a href="https://bitnami.com/stack/weblate/cloud/google"><img src="/media/gcp.png" /></a>
<a href="https://bitnami.com/stack/weblate/cloud/amazon"><img src="/media/aws.png" /></a>
<a href="https://bitnami.com/stack/weblate/cloud/azure"><img src="/media/azure.png" /></a>

<h2>{% trans "Code" %}</h2>

<p>
{% blocktrans %}Weblate is being developed on <a href="https://github.com/WeblateOrg/weblate">GitHub</a>, you can fork it there or just:{% endblocktrans %}
</p>

<pre>
# Weblate
git clone https://github.com/WeblateOrg/weblate.git

# {% trans "Weblate command line client" %}
git clone https://github.com/WeblateOrg/wlc.git
</pre>

{% endblock %}

weblate_web/templates/hosting-ordered.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "Hosting Weblate" %}{% endblock %}
{% block header %}{% trans "Hosting Weblate" %}{% endblock %}
{% block description %}
{% block headline %}{% trans "Thank you for ordering hosting!" %}{% endblock %}
{% endblock %}

{% block content %}

<h2>{% trans "Next steps" %}</h2>

<p>{% trans "The project setup is currently manual. If you haven't done so already, please get in touch with us and send us details about your repository setup." %}</p>

<p>{% trans "Usually following information is needed:" %}</p>

<ul>
<li>{% trans "URL of repository with translations." %}</li>
<li>{% trans "Path to translations within the repository." %}</li>
</ul>

<p>{% trans "You have to allow Weblate to access your repository. This can be done by adding Weblate user to your project (on GitHub, Bitbucket or GitLab) or adding SSH key we will provide you." %}</p>

{% endblock %}

weblate_web/templates/terms.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "Terms of Service" %}{% endblock %}
{% block header %}{% trans "Terms of Service and Privacy Policy" %}{% endblock %}
{% block description %}
{% block headline %}{% trans "The legal documents necessary to offer this service." %}{% endblock %}
{% endblock %}
{% block content %}

<div class="container-fluid">

<div class="card card-primary mb-4">
<div class="card-header">{% trans "Terms of Service" %}</div>
<div class="card-body tos">
{% include "legal/documents/tos.html" %}
</div>
</div>

<div class="card card-primary">
<div class="card-header">{% trans "Privacy Policy" %}</div>
<div class="card-body tos">
{% include "legal/documents/privacy.html" %}
</div>
</div>

</div>
{% endblock %}